version: 0.0
os: linux
files:
  - source: /
    destination: /srv/app
hooks:
  ApplicationStop:
    - location: deploy/stop.sh
      timeout: 300
  # AfterInstall:
  #   - TODO copy dotenv file from S3
  ApplicationStart:
    - location: deploy/start.sh
      timeout: 300
