# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8e6d4978f3bd9da1bf7559368192d3f0707649c6aaeb12e75c5f68f02ae9918dcd8adbf40801717141a59a63dbbd8d3448828697ed34b3e672fe1ff02bba207

test:
  secret_key_base: 76e1604be6ed0a8b3fbc9da001b9cdc38a8df4a0d2f734752e32160813a5fdd97471fcb5c4d0a74777b971a0674c9e42418485ffe4df0da451de1a5d9b4f4f20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
